### PR TITLE
REGD-1 update valis version

### PR DESCRIPTION
**Pull request by emro**
Update Valis version and incorporate @leepc12's changes to display a highlight range instead of a highlight coordinate

### CODE REVIEW

**Review by leepc12 — APPROVED** [review]
LGTM

**Comment by emro** [comment]
I updated because @leepc12 noticed that the track labels were not appearing on the gene track.

**Review by leepc12 — APPROVED** [review]
LGTM

**Review by leepc12 — APPROVED** [review]
LGTM

**Pull request merged**
